export const EASY = [
{c:"LA",p:1,q:"What comes next in the sequence?",seq:"3   6   12   24   48   ?",o:["72","96","84","100"],a:1},
{c:"LA",p:1,q:"What letter comes next?",seq:"A   C   E   G   I   ?",o:["J","K","L","M"],a:1},
{c:"LA",p:1,q:"All rows follow the same multiplication rule. What number replaces the ?",m:[[1,2,3],[2,4,6],[3,6,"?"]],o:["7","8","9","12"],a:2},
{c:"LA",p:1,q:"Which does NOT belong with the others?",seq:"Apple   Banana   Carrot   Mango   Grape",o:["Apple","Banana","Carrot","Mango"],a:2},
{c:"LA",p:1,q:"What comes next?",seq:"2   4   8   16   ?",o:["24","28","32","36"],a:2},
{c:"MA",p:1,q:"Find the next number in the series.",seq:"5   10   15   20   25   ?",o:["28","30","32","35"],a:1},
{c:"MA",p:1,q:"Find the next number.",seq:"1   4   9   16   25   ?",o:["30","34","36","49"],a:2},
{c:"MA",p:1,q:"If 5 workers take 8 hours to build a wall, how long would 10 workers take (same rate)?",o:["2 hrs","4 hrs","6 hrs","8 hrs"],a:1},
{c:"MA",p:1,q:"What comes next?",seq:"100   99   97   94   90   ?",o:["83","84","85","86"],a:2},
{c:"PS",p:1,q:"Tom is taller than Sam. Sam is taller than Pete. Who is the shortest?",o:["Tom","Sam","Pete","Cannot determine"],a:2},
{c:"PS",p:1,q:"All Bloops are Razzles. All Razzles are Lazzles. Which is definitely true?",o:["All Bloops are Lazzles","All Lazzles are Bloops","Some Razzles are not Lazzles","None of these"],a:0},
{c:"PS",p:1,q:"Mary's father has 5 daughters: Nana, Nene, Nini, Nono, and ___. What is the fifth daughter's name?",o:["Nunu","Nana","Mary","Cannot tell"],a:2},
{c:"VR",p:1,q:"CAT is to KITTEN as DOG is to:",o:["Puppy","Cub","Foal","Lamb"],a:0},
{c:"VR",p:1,q:"Which word is closest in meaning to HAPPY?",o:["Melancholy","Joyful","Angry","Weary"],a:1},
{c:"VR",p:1,q:"DOCTOR is to HOSPITAL as JUDGE is to:",o:["Police","Crime","Court","Law"],a:2},
{c:"WM",p:1,memseq:"8 - 3 - 7 - 1 - 5",q:"Mentally sort those numbers from lowest to highest. What is the MIDDLE (3rd) number?",o:["3","5","7","8"],a:2},
{c:"WM",p:1,memseq:"RED - BLUE - GREEN - YELLOW",q:"Reverse the order of those colours. What is the 2nd colour in the reversed list?",o:["Red","Blue","Green","Yellow"],a:2},
{c:"SP",p:1,fast:true,q:"Which of these four strings is DIFFERENT from the others?",o:["7F3M9P","7F3M9P","7F3N9P","7F3M9P"],a:2},
{c:"SP",p:1,fast:true,q:"Which pair of numbers adds up to exactly 100?",o:["43 + 58","19 + 81","22 + 79","17 + 84"],a:1},
{c:"SR",p:1,svgKey:"arrow_up",q:"The arrow shown points UP. After rotating it 90 degrees clockwise, which direction does it point?",o:["Up","Right","Down","Left"],a:1}
];
export const MEDIUM = [
{c:"LA",p:2,q:"What letter comes next in the sequence?",seq:"B   D   G   K   P   ?",o:["T","U","V","W"],a:2},
{c:"LA",p:2,q:"Each row follows the same rule. What is the missing value?",m:[[9,3,1],[25,5,1],[49,7,"?"]],o:["1","3","7","49"],a:0},
{c:"LA",p:2,q:"Find the next number in this series of prime numbers.",seq:"2   3   5   7   11   13   ?",o:["14","15","17","19"],a:2},
{c:"LA",p:2,q:"Which number does NOT belong?",seq:"144   169   196   200   225",o:["144","169","200","225"],a:2},
{c:"LA",p:2,q:"What is the next number in this famous series?",seq:"1   1   2   3   5   8   13   ?",o:["17","18","20","21"],a:3},
{c:"LA",p:2,q:"Which word does NOT belong with the others?",seq:"HEAT   BEAT   MEAT   FEAT   COAT",o:["HEAT","BEAT","COAT","FEAT"],a:2},
{c:"MA",p:2,q:"What is the next number in the series?",seq:"3   8   15   24   35   ?",o:["44","46","48","50"],a:2},
{c:"MA",p:2,q:"Find the next term.",seq:"2   6   12   20   30   ?",o:["36","40","42","44"],a:2},
{c:"MA",p:2,q:"A train travels 300 km in 2.5 hours. What is its average speed?",o:["100 km/h","110 km/h","120 km/h","130 km/h"],a:2},
{c:"MA",p:2,q:"This sequence uses two alternating operations. What comes next?",seq:"2   6   7   21   22   ?",o:["44","66","67","88"],a:1},
{c:"PS",p:2,q:"Three friends each own a different pet: cat, dog, or fish. Alice does not own the fish. Bob owns neither the cat nor the dog. Carol does not own the cat. Who owns the cat?",o:["Alice","Bob","Carol","Cannot determine"],a:0},
{c:"PS",p:2,q:"A man walks 3 km North, then 4 km East. How far is he from his starting point?",o:["3 km","4 km","5 km","7 km"],a:2},
{c:"PS",p:2,q:"In 6 years Tom will be twice as old as Jane was 2 years ago. Jane is currently 16. How old is Tom now?",o:["18","20","22","24"],a:2},
{c:"VR",p:2,q:"Which word is closest in meaning to EPHEMERAL?",o:["Eternal","Massive","Fleeting","Turbulent"],a:2},
{c:"VR",p:2,q:"TACITURN is to LOQUACIOUS as TORPID is to:",o:["Lethargic","Placid","Vivacious","Inert"],a:2},
{c:"VR",p:2,q:"Which word is closest in meaning to MENDACIOUS?",o:["Truthful","Duplicitous","Generous","Ambitious"],a:1},
{c:"VR",p:2,q:"ARCHIPELAGO is to ISLANDS as CONSTELLATION is to:",o:["Planets","Stars","Galaxies","Nebulae"],a:1},
{c:"WM",p:2,memseq:"4 - 8 - 2 - 9 - 5 - 1",q:"Mentally add 3 to every number. What is the SUM of the 1st and 3rd results (after adding 3 to each)?",o:["9","12","14","15"],a:2},
{c:"WM",p:2,memseq:"F - 3 - R - 7 - M - 2 - K",q:"Count only the LETTERS at odd positions (positions 1, 3, 5, 7). How many letters are there?",o:["2","3","4","5"],a:1},
{c:"SP",p:2,fast:true,q:"Which of these four strings is DIFFERENT from the others?",o:["8Bd4kT","8Bd4kT","8Bd4KT","8Bd4kT"],a:2},
{c:"SP",p:2,fast:true,q:"How many times does the digit 3 appear? 13, 3, 33, 31, 73, 3, 113, 303",o:["8","9","10","11"],a:2},
{c:"SP",p:2,fast:true,q:"Which of the following does NOT equal 144?",o:["12 x 12","288 / 2","16 x 9","9 x 15"],a:3},
{c:"SR",p:2,svgKey:"cube_staircase",q:"How many unit cubes make up this 3-step staircase? Count ALL cubes including those hidden underneath.",o:["4","6","8","9"],a:1},
{c:"SR",p:2,svgKey:"cross_net",q:"This cross-shaped net is folded along all edges into a 3D shape. What shape does it form?",o:["Cube","Triangular Prism","Rectangular Box","Pyramid"],a:0},
{c:"SR",p:2,svgKey:"lshape",q:"The L-shape shown is rotated 90 degrees clockwise. Where does the short horizontal base end up?",o:["Top-right corner","Top-left corner","Bottom-right corner","Bottom-left corner"],a:0}
];
export const HARD = [
{c:"LA",p:3,q:"What letter comes next? Hint: think about the initial letters of spoken numbers.",seq:"O   T   T   F   F   S   S   E   N   ?",o:["E","N","S","T"],a:3},
{c:"LA",p:3,q:"FRIEND encodes as HUMJTK (each letter shifted +2,+3,+4,+5,+6,+7). What does CANDLE encode to?",o:["EDRIRL","FDQGMK","ECPFOT","DCQINK"],a:0},
{c:"LA",p:3,q:"Each cell equals the column number raised to the power of the row number. What is the missing value?",m:[[2,4,4],[3,5,9],[4,6,"?"]],o:["12","14","16","18"],a:2},
{c:"MA",p:3,q:"Find the next number in this series.",seq:"3   5   9   17   33   ?",o:["55","60","65","70"],a:2},
{c:"MA",p:3,q:"What comes next?",seq:"1   2   6   24   120   ?",o:["480","600","720","840"],a:2},
{c:"PS",p:3,q:"Of 40 students, 20 study French, 18 study Spanish, and 8 study both. How many study neither?",o:["6","8","10","12"],a:2},
{c:"PS",p:3,q:"A clock shows exactly 3:15. What is the PRECISE angle between the minute and hour hands?",o:["0 degrees","7.5 degrees","15 degrees","22.5 degrees"],a:1},
{c:"VR",p:3,q:"Which word is closest in meaning to PERSPICACIOUS?",o:["Confused","Reckless","Astute","Stubborn"],a:2},
{c:"VR",p:3,q:"Which word is closest in meaning to SANGUINE?",o:["Pessimistic","Furious","Optimistic","Sorrowful"],a:2},
{c:"VR",p:3,q:"PLATITUDE is to CLICHE as PARADOX is to:",o:["Agreement","Solution","Contradiction","Simplicity"],a:2},
{c:"WM",p:3,memseq:"9 - 4 - 6 - 2 - 8 - 5 - 3",q:"Mentally double each number, then sum only those doubled results that are LESS than 10. What is that sum?",o:["8","10","14","18"],a:2},
{c:"WM",p:3,memseq:"J - 4 - P - 9 - B - 2 - T - 7",q:"Take only the NUMBERS from the sequence. What is the difference between the largest and smallest of those numbers?",o:["5","6","7","9"],a:2},
{c:"SP",p:3,fast:true,q:"Numbers should sum to exactly 100: 17, 23, 14, ___, 19, 11. What is the missing number?",o:["14","16","18","20"],a:1},
{c:"SR",p:3,svgKey:"fold_diagram",q:"A square paper is folded right-to-left, then bottom-to-top. A hole is punched at the top-right of the folded square (shown in orange). How many holes appear when fully unfolded?",o:["1 hole","2 holes","4 holes","8 holes"],a:2},
{c:"SR",p:3,svgKey:"top_view_object",q:"Looking at this 3D object from DIRECTLY ABOVE (bird's eye view), which footprint shape would you see?",o:["Large rectangle","Small square","L-shape","Two separate squares"],a:0}
];
export const shuf = (a: any[]) => { let b = a.slice(); for(let i=b.length-1; i>0; i--) { let j = Math.floor(Math.random()*(i+1)); let t = b[i]; b[i] = b[j]; b[j] = t; } return b; };
